apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphql # Application name
  namespace: argocd # Argocd namespace installation

spec:
  destination:
    # Destination cluster url
    server: "https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-9mqhw"
    # Application deployment namespace
    namespace: default

  # project name
  project: default
  source:
    repoURL: https://forge.softwareheritage.org/source/swh-charts.git
     # Branch content helm charts
    targetRevision: master
    # helm chart path
    path: swh-graphql/
    helm:
      # release name same as application name
      releaseName: graphql
      valueFiles: # list of values files
        - values/default.yaml
        - values/staging.yaml

  # Custom sync policy and automate task
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
