apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-metallb-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.5
    helm:
      releaseName: metallb
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-2mwgb
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - RespectIgnoreDifferences=true

  ignoreDifferences:
  # The ca bundle is updated by the controller during the runtime
  - group: 'apiextensions.k8s.io'
    kind: 'CustomResourceDefinition'
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
