---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: deposit-auth-secrets-vss
  namespace: swh
spec:
  destination:
    create: true
    name: deposit-auth-secrets
    overwrite: true
  mount: secrets-archive-staging-rke2
  path: deposit-auth-secrets
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: deposit-auth-secrets-vss
  namespace: swh-cassandra
spec:
  destination:
    create: true
    name: deposit-auth-secrets
    overwrite: true
  mount: secrets-archive-staging-rke2
  path: deposit-auth-secrets
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: deposit-auth-secrets-vss
  namespace: swh-cassandra-next-version
spec:
  destination:
    create: true
    name: deposit-auth-secrets
    overwrite: true
  mount: secrets-archive-staging-rke2
  path: deposit-auth-secrets
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
