---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-servers-svc
  namespace: cassandra
  labels:
    app: cassandra
spec:
  type: ExternalName
  externalName: "fake-url"
  selector:
    app: cassandra
  ports:
    - name: jmx-exporter
      port: 7070
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
    name: cassandra-servers-svc
    namespace: cassandra
    labels:
        app: cassandra
subsets:
    - addresses:
      - ip: 192.168.130.181
      - ip: 192.168.130.182
      - ip: 192.168.130.183
      ports:
        - name: jmx-exporter
          port: 7070
          protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: cassandra
  name: cassandra-jmx-exporter
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  namespaceSelector:
    any: true
  endpoints:
    - port: jmx-exporter
      interval: 30s
      honorLabels: true
      relabelings:
        # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
        - sourceLabels:
            - __address__
          targetLabel: __address__
          regex: "192.168.130.18(\\d)(.*)"
          replacement: "cassandra$1.internal.staging.swh.network$2"
          action: replace
