---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: reaper-secrets-vss
  namespace: cassandra
spec:
  destination:
    create: true
    name: reaper-secrets
    overwrite: true
  mount: secrets-archive-staging-rke2
  path: reaper-secrets
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth