---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: swh-osporadar-secret-vss
  namespace: osporadar
spec:
  destination:
    create: true
    name: swh-osporadar-secret
    overwrite: true
  mount: secrets-archive-staging-rke2
  path: swh-osporadar-secret
  refreshAfter: 30s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
