---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gandi-credentials-vss
  namespace: cert-manager
spec:
  destination:
    create: true
    name: gandi-credentials
    overwrite: true
  mount: secrets-rancher
  path: gandi-credentials
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
