---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rancher-backup-credentials-vss
  namespace: cattle-system
spec:
  destination:
    create: true
    name: rancher-backup-credentials
    overwrite: true
  mount: secrets-rancher
  path: rancher-backup-credentials
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
