---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: thanos-objstore-config-secret-vss
  namespace: monitoring
spec:
  destination:
    create: true
    name: thanos-objstore-config-secret
    overwrite: true
  mount: secrets-rancher
  path: thanos-objstore-config-secret
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
