---
# Namespace dedicated to keda
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
# Namespace dedicated to the swh services (e.g. loaders, rpc, ...)
apiVersion: v1
kind: Namespace
metadata:
  name: swh
---
# Namespace dedicated to cluster monitoring services
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-provisioner
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
