# Declare the application to manage bithami charts
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archive-staging-bitnami
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami
    repoURL: "https://charts.bitnami.com/bitnami"
    helm:
      releaseName: bitnami
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-cx2bq
    namespace: bitnami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
