{
 "title": "Cassandra",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"cassandra-.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client request timeout",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_clientrequest_timeouts_count{instance=~\"${instance}.*\"}[$__rate_interval]) >0",
     "legendFormat": "{{instance}} - {{clientrequest}}"
    }
   ]
  },
  {
   "title": "Oversized mutations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_commitlog_oversizedmutations_count{instance=~\"${instance}.*\"}",
     "legendFormat": "{{instance}} - {{clientrequest}}"
    }
   ]
  },
  {
   "title": "Data occupation per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_totaldiskspaceused{instance=~\"${instance}.*\"}) by (instance)",
     "legendFormat": "{{instance}} - {{clientrequest}}"
    }
   ]
  },
  {
   "title": "Commitlog size  per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_commitlog_totalcommitlogsize{instance=~\"${instance}.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending  Hints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_totalhintsinprogress_count{instance=~\"${instance}.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total hints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_totalhints_count{instance=~\"${instance}.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending  Compaction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_pendingcompactions{keyspace='', instance=~\"${instance}.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "partition size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_maxpartitionsize{keyspace=\"\",instance=~\"${instance}.*\"} > 0"
    }
   ]
  },
  {
   "title": "Unrepaired size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (keyspace, table) ( cassandra_table_bytesunrepaired{instance=~\"${instance}\", keyspace != \"\"})",
     "legendFormat": "{{keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Repair job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_repairjobsstarted{instance=~\"${instance}.*\"} - cassandra_table_repairjobscompleted{instance=~\"${instance}.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}