---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: gitlab-system
spec:
  instances: 1
  storage:
    size: 15Gi
  walStorage:
    size: 3Gi
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 16

  bootstrap:
    initdb:
      owner: gitlab
