apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archive-staging-rke2-eck-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.6.1
    helm:
      releaseName: eck-operator
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-9n5h9nrf
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: '*'
      kind: ValidatingWebhookConfiguration
      name: elastic-operator.elastic-system.k8s.elastic.co
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        # Use the following to ease looking out for data to ignore
        # kubectl --context archive-staging-rke2 \
        #   get ValidatingWebhookConfiguration elastic-operator.elastic-system.k8s.elastic.co \
        #   -o json | jq ".webhooks[].clientConfig.caBundle"
