# Declare the application to manage keda
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archive-staging-rke2-keda
  namespace: argocd
spec:
  project: default
  source:
    chart: keda
    repoURL: "https://kedacore.github.io/charts"
    targetRevision: 2.9.1
    helm:
      releaseName: keda
      values: |
        metricsServer:
          enabled: true
        prometheus:
          metricsServer:
            enabled: true
            podMonitor:
              enabled: true
          operator:
            enabled: true
            podMonitor:
              enabled: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-9n5h9nrf
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
