# Application that gets started when a new MR is spawned in swh-charts with the
# swh-next-version branch (for new releases).
# This spawns the new swh services in the "swh-cassandra-next-version" namespace in the
# archive-staging-rke2 cluster
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: swh-cassandra-next-version
  namespace: argocd
spec:
  generators:
  - pullRequest:
      gitlab:
        project: '77'
        api: https://gitlab.softwareheritage.org
        pullRequestState: opened
      filters:
      - branchMatch: "swh-next-version"
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'swh-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-charts.git'
        path: swh
        targetRevision: "{{branch}}"
        helm:
          valueFiles:
            - ../values-swh-application-versions.yaml
            - values/default.yaml
            - values/staging/default.yaml
            - values/staging/swh-cassandra-next-version.yaml
          releaseName: next-version-{{number}}
      project: default
      destination:
        server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-9n5h9nrf
        namespace: swh-cassandra-next-version
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
