apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-argocd-install
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  users.anonymous.enabled: "true"
  accounts.vsellier: apiKey, login
