# manually install
# kubectl apply -f app1.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  annotations:
    # required for collector configured as mode 'sidecar'
    sidecar.opentelemetry.io/inject: "true"
spec:
  containers:
  - name: app1
    image: jaegertracing/vertx-create-span:operator-e2e-tests
    ports:
      - containerPort: 8080
        protocol: TCP
