# manually install (after installing the operator through helm)
# kubectl apply -f opentelemetry-collector.yaml
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: default
spec:
  mode: sidecar
  # mode: statefulset
  # replicas: 3
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      elasticsearch/log:
        # can be replaced by using the env variable ELASTICSEARCH_URL
        endpoints:
          - https://elasticsearch-master:9200
        user: elastic
        password: foobar
        api_key:
        tls:
          insecure_skip_verify: true
        logs_index: logs-generic-default

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters:
            - elasticsearch/log
