---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:
        loglevel: info

    # elasticsearch/trace:
    #   endpoints:
    #     - https://elasticsearch-master:9200
    #   user: elasticsearch
    #   password: 0YucK4zZ2Xx0tLzQ
    #   api_key:
    #   tls:
    #     insecure_skip_verify: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters:
            - logging
            # - elasticsearch/trace
