---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-staging-rke2-redis
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: 'https://ot-container-kit.github.io/helm-charts/'
    targetRevision: 0.15.11
    helm:
      releaseName: redis
      values: |
        serviceMonitor:
          enabled: true
          namespace: redis
        redisExporter:
          enabled: true
        nodeSelector:
          kubernetes.io/hostname: rancher-node-staging-rke2-worker1
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-persistent
              accessModes: ["ReadWriteOnce"]
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-hb9j7h5g
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
