# Declare the application to manage keda
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archive-production-local-path-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rancher/local-path-provisioner.git"
    path: deploy/chart/local-path-provisioner
    targetRevision: v0.0.23
    helm:
      releaseName: local-path-provisioner
      values: |
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /tmp/k8s-ephemeral-storage
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-2mwgb
    namespace: local-path-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
