# Declare the application to manage cert-manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-certmanager
  namespace: argocd
spec:
  revisionHistoryLimit: 2
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.10.0
    helm:
      releaseName: rancher-certmanager # must match the application name (https://github.com/argoproj/argo-cd/issues/2871)
      parameters:
        - name: "installCRDs"
          value: "true"
      values: |
          prometheus:
            enabled: true
            servicemonitor:
              enabled: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/local
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: rancher-certmanager-cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
