apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-ingress-nginx-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.0
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            loadBalancerIP: 10.240.0.100
          watchIngressWithoutClass: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/local
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
