apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-application
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: "https://releases.rancher.com/server-charts/latest"
    targetRevision: 2.6.9
    helm:
      releaseName: rancher
      values: |
        hostname: rancher.euwest.azure.internal.softwareheritage.org
        # ingress:
        #   extraAnnotations:
        #     cert-manager.io/cluster-issuer: letsencrypt-production-gandi
        #     kubernetes.io/tls-acme: "true"
        #   tls:
        #   - hosts:
        #     - rancher.azure.internal.softwareheritage.org
        #     secretName: tls-rancher-ingress
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/local
    namespace: cattle-system
  syncPolicy:
    automated:
      # Be careful with this app
      prune: false
  ignoreDifferences:
    - group: '*'
      kind: ServiceMonitor
      name: rancher-prometheus-kube-pr-kubelet
      jqPathExpressions:
        - .spec.endpoints[].relabelings
