# Application applying the secrets on the production-cassandra cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archive-staging-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@gitlab.softwareheritage.org/infra/ci-cd/k8s-swh-private-data.git
    targetRevision: HEAD
    path: archive-staging
    directory:
      recurse: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-cx2bq
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
