---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-node1
  labels:
    prometheus: "true"
spec:
  capacity:
    storage: 35Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce # required
  local:
    path: "/srv/prometheus/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher-node-cassandra1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-node2
  labels:
    prometheus: "true"
spec:
  capacity:
    storage: 35Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce # required
  local:
    path: "/srv/prometheus/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher-node-cassandra2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-node3
  labels:
    prometheus: "true"
spec:
  capacity:
    storage: 35Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce # required
  local:
    path: "/srv/prometheus/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher-node-cassandra3

