---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: longhorn
parameters:
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  allowVolumeExpansion: true
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    name: longhorn-2replicas
  parameters:
    fromBackup: ""
    fsType: ext4
    numberOfReplicas: "2"
    staleReplicaTimeout: "30"
  provisioner: driver.longhorn.io
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
