---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-staging-rke2-metallb-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.130.209/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - test-staging-rke2-metallb-pool
  nodeSelectors:
    - matchExpressions:
      - key: "swh/metallbExclude"
        operator: DoesNotExist
