---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-test-bucket-secret-vss
  namespace: cnpg
spec:
  destination:
    create: true
    name: minio-test-bucket-secret
    overwrite: true
  mount: secrets-test-staging-rke2
  path: minio-test-bucket-secret
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
