# Needed to internally expose thanos
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-blackbox-exporter-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: prometheus-blackbox-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 7.1.3
    helm:
      releaseName: admin-blackbox-exporter-application
      # Complete values.yaml example available at:
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml
      values: |
        serviceMonitor:
          enabled: true
          selfMonitor:
            enabled: true
          prometheusRule:
            enabled: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-q2wd4
    namespace: cattle-monitoring-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
