# Declare the application to manage cert-manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-certmanager
  namespace: argocd
spec:
  revisionHistoryLimit: 2
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.10.0
    helm:
      releaseName: cert-manager
      parameters:
        - name: "installCRDs"
          value: "true"
      values: |
          # this is necessary to not retrieve the SOA fields from internal zone
          extraArgs:
            - --dns01-recursive-nameservers=ns-246-a.gandi.net:53,ns-239-b.gandi.net:53,ns-228-c.gandi.net:53
            - --dns01-recursive-nameservers-only
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-q2wd4
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
