# Needed to internally expose thanos
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-nfs-provisioner-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.17
    helm:
      releaseName: admin-nfs-provisioner-application
      values: |
        nfs:
          server: saam.internal.softwareheritage.org
          path: /srv/storage/space/minio-data
        storageClass:
          name: nfs-volume
          reclaimPolicy: Retain
          accessModes: ReadWriteMany
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-q2wd4
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
