# Needed to internally expose thanos
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-ingress-nginx-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.5
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            annotations:
              metallb.universe.tf/allow-shared-ip: internalIP
          ingressClassResource:
            default: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-q2wd4
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
