# See https://gitlab.softwareheritage.org/infra/ci-cd/3rdparty/alertmanager-irc-relay/-/tree/master
# for more information
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-irc-relay
  namespace: cattle-monitoring-system
data:
  # For more information, check
  # https://gitlab.softwareheritage.org/infra/ci-cd/3rdparty/alertmanager-irc-relay/-/tree/master#configuring-and-running-the-bot
  config: |
    http_host: 0.0.0.0
    http_port: 8000
    irc_host: irc.eu.libera.chat
    irc_port: 7000
    irc_nickname: $IRC_USER
    irc_nickname_password: $IRC_PASSWORD
    irc_realname: SWH AlertManager IRC Bot

    irc_channels:
      - name: "#swh-sysadm"

    # Define how IRC messages should be sent.
    #
    # Send only one message when webhook data is received.
    # Note: By default a message is sent for each alert in the webhook data.
    msg_once_per_alert_group: no

    # Define how IRC messages should be formatted.
    #
    # The formatting is based on golang's text/template .
    # msg_template: "Alert {{ .Labels.alertname }} on {{ .Labels.instance }} is {{ .Status }}"
    msg_template: "Alert {{ .Labels.severity | ToUpper }} {{ .Status }} - {{ .Labels.environment }}/{{ .Labels.cluster }} - {{ .Labels.alertname }} - {{ .Annotations.description }}"

    # Set the internal buffer size for alerts received but not yet sent to IRC.
    alert_buffer_size: 2048
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-irc-relay
  namespace: cattle-monitoring-system
spec:
  selector:
    app: alertmanager-irc-relay
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-irc-relay
  namespace: cattle-monitoring-system
spec:
  selector:
    matchLabels:
      app: alertmanager-irc-relay
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: alertmanager-irc-relay
    spec:
      containers:
        - name: irc-relay
          image: container-registry.softwareheritage.org/infra/ci-cd/3rdparty/alertmanager-irc-relay:v0.5.0
          command:
            - alertmanager-irc-relay
            - --config=/etc/ircrelay/config.yml
          env:
            - name: IRC_USER
              valueFrom:
                secretKeyRef:
                  name: alertmanager-irc-relay
                  key: user
                  # 'name' secret must exist & include that ^ key
                  optional: false
            - name: IRC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alertmanager-irc-relay
                  key: password
                  # 'name' secret must exist & include that ^ key
                  optional: false
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: configuration
              mountPath: /etc/ircrelay
      volumes:
        - name: configuration
          configMap:
            name: alertmanager-irc-relay
            defaultMode: 0660
            items:
              - key: "config"
                path: "config.yml"
