# from https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/
---
# Service monitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: argocd
  name: argocd-metrics
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  namespaceSelector:
    matchNames:
     - argocd
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: argocd
  name: argocd-notifications-controller-metrics
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller-metrics
  namespaceSelector:
    matchNames:
     - argocd
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: argocd
  name: argocd-server-metrics
  labels:
    app: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  namespaceSelector:
    matchNames:
     - argocd
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      path: /metrics
---
# Alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: argocd
  name: argocd-alertmanager.rules
  namespace: argocd
spec:
  groups:
  - name: argocd.rules
    rules:
    - alert: ArgoCDApplicationNotHealthy
      annotations:
        description: The application {{ $labels.name }} is not healthy since more than 1h.
        summary: An argocd application is not healthy
      expr: |-
        max_over_time(argocd_app_info{health_status='Progressing'}[5m]) == 1
      for: 1h
      labels:
        severity: critical
        namespace: cattle-monitoring-system
    - alert: ArgoCDApplicationOutOfSyncWarning
      annotations:
        description: The application {{ $labels.name }} is out of sync since more than 1h.
        summary: An argocd application is out of sync
      expr: |-
        max_over_time(argocd_app_info{sync_status='OutOfSync'}[5m]) == 1
      for: 1h
      labels:
        severity: warning
        namespace: cattle-monitoring-system
    - alert: ArgoCDApplicationOutOfSyncCritical
      annotations:
        description: The application {{ $labels.name }} is out of sync since more than 1d.
        summary: An argocd application is out of sync
      expr: |-
        max_over_time(argocd_app_info{sync_status='OutOfSync'}[5m]) == 1
      for: 1d
      labels:
        severity: critical
        namespace: cattle-monitoring-system
    - alert: ArgoCDClusterConnectionLost
      annotations:
        description: The connection to the cluster {{ $labels.server }} is lost since more the 1h.
        summary: An argocd cluster is unreachable
      expr: |-
        max_over_time(argocd_cluster_connection_status{}[5m]) == 0
      for: 1h
      labels:
        severity: critical
        namespace: cattle-monitoring-system
    - alert: ArgoCDInternalRedisError
      annotations:
        description: Argocd internal redis error rate detected
        summary: Failing redis queries detected
      expr: |-
        max_over_time (rate(argocd_redis_request_total{failed="true"}[5m])[60m:1m]) > 0
      for: 1h
      labels:
        severity: warning
        namespace: cattle-monitoring-system
