# Needed to internally expose thanos
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-staging-ingress-nginx-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.5
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          ingressClassResource:
            default: false # be sure to not interfere with gitlab-ingress class
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            externalTrafficPolicy: Local
            loadBalancerIP: 10.240.0.100
          # internal:
          #   enabled: true
          #   externalTrafficPolicy: Local
  destination:
    server: https://192.168.200.13
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
