# Declare the argocd application application applying the argocd directory
# content to the argocd cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-rke2-argocd-applications
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    repoURL: https://gitlab.softwareheritage.org/swh/infra/ci-cd/k8s-clusters-conf.git
    targetRevision: master
    path: argocd-configuration
    directory:
      recurse: true
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-682nvssh
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

