# Needed to internally expose thanos
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-rke2-keycloak-operator
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources
    targetRevision: 26.7.3
    path: kubernetes
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-682nvssh
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
