# Declare the application to deploy the swh services
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-rke2-argocd-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: v6.0.14
    helm:
      releaseName: argocd
      values: |
        global:
          networkPolicy:
            create: true

        redis-ha:
          enabled: true

        controller:
          replicas: 1
          metrics:
            enabled: true

        server:
          replicas: 2
          metrics:
            enabled: true

        repoServer:
          replicas: 2
          metrics:
            enabled: true

        notifications:
          metrics:
            enabled: true

        applicationSet:
          replicas: 1
          metrics:
            enabled: true

        secret:
          createSecret: false

        configs:
          cm:
            application.instanceLabelKey: app.kubernetes.io/instance
            users.anonymous.enabled: "true"
            accounts.vsellier: apiKey, login
            accounts.olasd: apiKey, login
            accounts.ardumont: apiKey, login
            accounts.gsamson: apiKey, login
          params:
            # Enable ApplicationSet applicationsSync policy override
            applicationsetcontroller.enable.policy.override: true
          rbac:
            policy.default: role:readonly
            policy.csv: |
              g, vsellier, role:admin
              g, olasd, role:admin
              g, ardumont, role:admin
              g, gsamson, role:admin
          ssh:
            extraHosts: |
              forge.softwareheritage.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIEv052pq1mvCDxaP+IBjYSEiAAjUwX+rLl1Tc4ZJ8ck7+/JuR9uSiBspeF4E8M6YE0JFczGqpJdMeU5uf/rUqeMLp53g7Q9BWdIzHBOGLSW80NZ9SYLoPZdhiLd+W3nHu6tze79txvwSqbVpw91NRiaQT8MmI3f7gcRYKClmtODO9Sz8hIUIwGtty7/SJEpZC8httIbsY6jjGM/IUbh6FWsfN3G7jxoq8OvwErSZ+zkfJ6IpPdkTrPRCbGNaO8DDQOBdhGu1z1DXkXeaa6jD7t2SiTpJ1B6BgjwuefimczGNohUisLdtUFarAByb7iklpeMvbiS9N/TsxV88D8qMD
              forge.softwareheritage.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKLfgPwdf08OA0ajHnb89l+AvHk1Zg1MQiWCtaEwn6Em3pPQjoQ+mrm5afgoCd5aKrG2dlNnwZsHapP7p0AIcqc=
              forge.softwareheritage.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKsVk4jv4nkFQQGnxvpM503e420waZ4xqeTiEhCaa6pm
              gitlab.softwareheritage.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINHpuzSvXqYgdUHnuC4NKb6v4iHNhBYbzElOsYbAz1Ew
              gitlab.softwareheritage.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9bFauuRYyRMt8VhZVIkn+VOmCa5+ep9PtmZCpMiXEtA2paSxjOQ2JluGdtB0cQgRB1/yCnREOSk5yQB+38ZTW/86Q67HmAvndVlfnUgy/xD3SMzOpl5hKC8Y/8tZ0JAJNS7iZ/QSqV3xFsooYRis4wr27KWYpQro0e9qnU4nwBXBLHMGuxOAWZ/QScranUjcKFt9lr/4bTwMhaNHJm2kmNU2UX+oyEGRTQGFzLN3JytFZh3gLV2oiL6Z7/jnEg9YVUjYScC4gFSTaKApmxaQmF4XkceEvARHrrBIM/VzpRLEMVB1yAZrUvznLCGnoXjG4VfXWGxZC0KqzlejzzPUxej6A3IzEQeLPWv1pApZYcOSFhuGTeNOVGj23I9BxlA490hk+y3a+9IzLJiRWhEyLq6CX5q+XJHMIn+ABexhyXMjI/hVVknD3QtjUmqZ5+BzcQ/GtG4xh9OvKgmS354yscvCqm46QX151n0g/qnD2IC+Azg3rihb/r3KA50OGXzU=
              gitlab.softwareheritage.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB5gBaLsMb3qhKXkOF8gZgbC43jwXoOhtack93JMQ8otsrG5HscahbW/J3MAoAIUkPTZEwOWZynQGI9Z8KPyf5s=

  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-682nvssh
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2
