---
apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  namespace: keycloak
  name: keycloak
spec:
  instances: 1
  update:
    strategy: Auto
  db:
    vendor: postgres
    host: db-keycloak-rw
    usernameSecret:
      name: swh-keycloak-postgres-secret
      key: username
    passwordSecret:
      name: swh-keycloak-postgres-secret
      key: password
    database: keycloak
  features:
    enabled:
      - client-admin-api:v2
  http:
    httpEnabled: true
  hostname:
    hostname: auth.staging.swh.network
  ingress:
    enabled: true
    className: nginx
  proxy:
    headers: xforwarded
# Test additionalOption for debug
  additionalOptions:
    - name: metrics-enabled
      value: "true"

    - name: event-metrics-user-enabled
      value: "true"
    
    - name: event-metrics-user-events
      value: "true"