---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage
  annotations:
    pv.beta.kubernetes.io/gid: "42000"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-volume
  volumeMode: Filesystem
  nfs:
    path: /srv/storage/space/minio-data
    server: saam.internal.softwareheritage.org
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: minio
spec:
  volumeName: minio-storage
  storageClassName: nfs-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

