---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-secrets-vss
  namespace: minio
spec:
  destination:
    create: true
    name: minio-secrets
    overwrite: true
  mount: secrets-admin-rke2
  path: minio-secrets
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
