---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: netbox-postgresql-secret-vss
  namespace: netbox
spec:
  destination:
    create: true
    labels:
      cnpg.io/reload: 'true'
    name: netbox-postgresql-secret
    overwrite: true
    type: kubernetes.io/basic-auth
  mount: secrets-admin-rke2
  path: netbox-postgresql-secret
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
