# Source: cluster-config/templates/keycloak/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: swh-keycloak-postgres-secret-vss
  namespace: keycloak
spec:
  destination:
    create: true
    name: swh-keycloak-postgres-secret
    overwrite: true
  mount: secrets-admin-rke2
  path: swh-keycloak-postgres-secret
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth