# Declare the application applying the argocd applications
# basically apply the changes on this repository in argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-argocd-applications
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    repoURL: https://forge.softwareheritage.org/source/k8s-clusters-conf.git
    targetRevision: HEAD
    path: argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
