apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress-nginx-application
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 0.14.1
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: "controller.setAsDefaultIngress"
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
