---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-secret-vss
  namespace: rook-ceph
spec:
  destination:
    create: true
    name: admin-secret
    overwrite: true
    type: kubernetes.io/rook
  mount: secrets-archive-production-rke2
  path: admin-secret
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
