---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-checks-pvc
  namespace: swh-cassandra
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-checks-backup
  namespace: swh-cassandra
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-checks
  name: cassandra-checks
  namespace: swh-cassandra
spec:
  replicas: 6
  selector:
    matchLabels:
      app: cassandra-checks
  template:
    metadata:
      labels:
        app: cassandra-checks
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: swh/journal_client
                operator: In
                values:
                - "true"
      securityContext:
        fsGroup: 1000
      priorityClassName: swh-background-workload
      containers:
        - name: cassandra-checks
          command:
          - /opt/swh/entrypoint.sh
#          resources:
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          image: container-registry.softwareheritage.org/swh/infra/swh-apps/cassandra_checks:20240311.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: cassandra-checks-volume
            mountPath: /volume
          - name: cassandra-checks-volume2
            mountPath: /volume2
          - name: swh-config
            mountPath: /etc/swh/
          env:
          - name: SWH_CONFIG_FILENAME
            value: /etc/swh/config
      volumes:
        - name: cassandra-checks-volume
          persistentVolumeClaim:
            claimName: cassandra-checks-pvc
        - name: cassandra-checks-volume2
          persistentVolumeClaim:
            claimName: cassandra-checks-backup
        - name: swh-config
          secret:
            secretName: cassandra-check-config-secret
