---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production-metallb-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.100.139/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb
