---
# Namespace dedicated to deploy swh using cassandra as backend
apiVersion: v1
kind: Namespace
metadata:
  name: swh-cassandra
---
# Namespace for keda
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
# Namespace for cassandra monitoring
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
---
# Namespace dedicated to the swh elastic environment
apiVersion: v1
kind: Namespace
metadata:
  name: swh
---
# Namespace dedicated to the metallb environment
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
# Namespace dedicated to the ingress-nginx environment
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-provisioner
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: software-stories
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
---
apiVersion: v1
kind: Namespace
metadata:
  name: svix-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg
