---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: storage-replayer-broker-secret-vss
  namespace: swh-cassandra
spec:
  destination:
    create: true
    name: storage-replayer-broker-secret
    overwrite: true
  mount: secrets-archive-production-rke2
  path: storage-replayer-broker-secret
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
