apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-production-configuration
  namespace: argocd
spec:
  project: default # Todo define a project to limit the deployment types
  source:
    repoURL: https://gitlab.softwareheritage.org/infra/ci-cd/k8s-clusters-conf.git
    targetRevision: master
    path: gitlab-production
    directory:
      recurse: true
  destination:
    server: https://192.168.200.4
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
