apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-production-gitlab-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/gitlab-org/cloud-native/gitlab-operator.git
    targetRevision: 0.26.2
    path: deploy/chart
    helm:
      releaseName: gitlab-operator
  destination:
    server: https://192.168.200.4
    namespace: gitlab-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      kind: Deployment
      name: gitlab-controller-manager
      jqPathExpressions:
        - .spec.template.metadata.annotations
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: gitlab-validating-webhook-configuration
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")

