---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configuration
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        # Filter out the in-cluster cluster, for which we don't have a cluster-configuration
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{ .name }}-cluster-configuration'
      namespace: argocd
    spec:
      revisionHistoryLimit: 2
      project: default
      source:
        repoURL: 'https://gitlab.softwareheritage.org/swh/infra/k8s-clusters-conf.git'
        path: argocd-configuration/chart
        targetRevision: 'master'
        helm:
          valueFiles:
            - 'values/{{ .name }}.yaml'
          releaseName: '{{ .name }}-cluster-configuration'
      destination:
        # This chart deploys argocd Applications so we always apply it on the local cluster
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

