apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configuration
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: admin-rke2
        branch: production
      - cluster: archive-staging-rke2
        branch: staging
      - cluster: archive-production-rke2
        branch: production
      - cluster: test-staging-rke2
        branch: staging
      - cluster: gitlab-staging
        branch: production
      - cluster: gitlab-production
        branch: production
      - cluster: rancher
        branch: production
  template:
    metadata:
      name: '{{cluster}}-cluster-configuration'
      namespace: argocd
    spec:
      revisionHistoryLimit: 2
      project: default
      source:
        repoURL: 'https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-charts.git'
        path: cluster-configuration
        targetRevision: '{{branch}}'
        helm:
          valueFiles:
            - 'values/{{cluster}}.yaml'
          releaseName: '{{cluster}}-cluster-configuration'
      destination:
        # always apply the configuration on the argocd cluster
        server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-682nvssh
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

