---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-components
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  generators:
    - clusters:
        selector:
          matchLabels:
            softwareheritage.org/deploy-cluster-components: "true"
        values:
          branch: '{{ index .metadata.labels "softwareheritage.org/default-branch" }}'
  template:
    metadata:
      name: '{{ .name }}-cluster-components'
      namespace: argocd
    spec:
      revisionHistoryLimit: 2
      project: default
      source:
        repoURL: 'https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-charts.git'
        path: cluster-components
        targetRevision: '{{ .values.branch }}'
        helm:
          valueFiles:
            - 'values/default.yaml'
            - 'values/{{ .name }}.yaml'
          releaseName: '{{ .name }}-cluster-components'
      destination:
        name: '{{ .name }}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
