---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  applyNestedSelectors: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  softwareheritage.org/deploy-ceph: "true"
          - list:
              elements:
                - chart: rook-ceph
                  syncPolicy:
                    syncOptions:
                      - CreateNamespace=true
                  ignoreDifferences: []
                - chart: rook-ceph-cluster
                  syncPolicy:
                    syncOptions:
                      - RespectIgnoreDifferences=true
                      - CreateNamespace=true
                  ignoreDifferences:
                    - group: "ceph.rook.io"
                      kind: "CephCluster"
                      jsonPointers:
                        # Noise generated by the helm chart
                        - /spec/cephVersion/allowUnsupported
                        - /spec/healthCheck
                        - /spec/monitoring
                        - /spec/network/connections
                        # Unused for external clusters
                        - /spec/cleanupPolicy
                        - /spec/continueUpgradeAfterChecksEvenIfNotHealthy
                        - /spec/disruptionManagement
                        - /spec/mgr
                        - /spec/mon
                        - /spec/osd
                        - /spec/removeOSDsIfOutAndSafeToRemove
                        - /spec/resources/mgr
                        - /spec/resources/mon
                        - /spec/resources/osd
                        - /spec/skipUpgradeChecks
  template:
    metadata:
      name: "{{ .name }}-{{ .chart }}"
      namespace: argocd
    spec:
      destination:
        namespace: rook-ceph
        name: "{{ .name }}"
      project: default
      sources:
        - chart: "{{ .chart }}"
          repoURL: https://charts.rook.io/release
          targetRevision: "v1.13.4"
          helm:
            valueFiles:
              - "$values/argocd-configuration/cluster-components/values/{{ .chart }}/defaults.yaml"
              - "$values/argocd-configuration/cluster-components/values/{{ .chart }}/{{ .name }}.yaml"
            ignoreMissingValueFiles: true
            valuesObject:
              operatorNamespace: rook-ceph
        - repoURL: https://gitlab.softwareheritage.org/swh/infra/ci-cd/k8s-clusters-conf.git
          targetRevision: mr/rook-ceph-applicationset
          ref: values
  templatePatch: |
    spec:
      syncPolicy: {{ .syncPolicy | toJson }}
      ignoreDifferences: {{ .ignoreDifferences | toJson }}
