# Declare the application to manage local path provisioner
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archive-production-rke2-local-persistent-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rancher/local-path-provisioner.git"
    path: deploy/chart/local-path-provisioner
    targetRevision: v0.0.23
    helm:
      releaseName: local-persistent-provisioner
      values: |
        configmap:
          name: local-persistent-provisioner
        nameOverride: local-persistent-provisioner
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /srv/kubernetes/volumes/
        storageClass:
          create: true
          defaultClass: false
          name: local-persistent
          reclaimPolicy: Retain
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-75xcg59s
    namespace: local-path-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
