---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: software-stories-production-rke2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.softwareheritage.org/swh/infra/ci-cd/swh-charts.git'
    path: software-stories
    targetRevision: production
    helm:
      releaseName: software-stories
      parameters:
        - name: "host"
          value: stories.softwareheritage.org
  destination:
    server: https://rancher.euwest.azure.internal.softwareheritage.org/k8s/clusters/c-m-75xcg59s
    namespace: software-stories
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
