---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: swh-azure-storage-credentials-vss
  namespace: gitlab-system
spec:
  destination:
    create: true
    name: swh-azure-storage-credentials
    overwrite: true
  mount: secrets-gitlab-production
  path: swh-azure-storage-credentials
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: openbao-vso-auth
